### ISSUE TITLE
timestamps helper

### ISSUE THREAD

**Issue by marcstein** [elbywan/moongoon#10]
Sorry if this is kind of a dumb question...but I'm accustomed to including timestamps in a Mongoid class definition to automatically generate created_at and updated_at fields.

Is there an equivalent in Mongoon?

Thanks!

Marc

**Comment by elbywan** [comment]
Hey @marcstein,

> Is there an equivalent in Mongoon?

I'm not a `mongoid` expert but I think that you can replicate the behaviour by using [insert/update hooks](https://github.com/elbywan/moongoon/blob/master/src/models/database/hooks.cr):

```crystal
module Moongoon::Timestamps
  macro included
    property created_at : Time?
    property updated_at : Time?

    before_insert { |model|
      model.created_at = Time.utc
    }
    before_update { |model|
      model.updated_at = Time.utc
    }
  end
end

class MyModel < Moongoon::Collection
  include Moongoon::Timestamps
  collection "models"
  property text : String
end

MyModel.clear

model = MyModel.new(text: "A")
model.insert
puts model.to_json
# => {"_id":{"$oid":"60cd1c385c7281c67b6b7a06"},"created_at":"2021-06-18T22:20:40Z","text":"A"}
sleep 1.seconds
model.text = "B"
model.update
puts model.to_json
# => {"_id":{"$oid":"60cd1c385c7281c67b6b7a06"},"created_at":"2021-06-18T22:20:40Z","updated_at":"2021-06-18T22:20:41Z","text":"B"}
```

**Comment by marcstein** [comment]
Thanks, Julien, for both the answer and the great work!


Marc Stein CEO
underwrite.ai
P. (617) 545-7171   M. (857) 222-3291
E. ***@***.***
W. https://www.underwrite.ai
<https://www.linkedin.com/in/marc-stein-b83b765>
