### ISSUE TITLE
Mongo 4 support?

### ISSUE THREAD

**Issue by Nicolab** [elbywan/moongoon#9]
Hello,

Does Moongoon support Mongo version 4 (latest is 4.4.6)?

**Comment by elbywan** [comment]
Hey @Nicolab,

Moongoon relies on [`cryomongo`](https://github.com/elbywan/cryomongo) which does support Mongo 4. It is not tested against 4.4 and does not implement 4.4 features but it should still be compatible.

**Comment by Nicolab** [comment]
Ok thanks.
